apiVersion: apps/v1
kind: Deployment

metadata:
  name: ajay-panwala
  namespace: sonu
  labels:
    app: nginx

spec:
  replicas: 15

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
      - name: ajay-panwala2
        image: nginx:latest
        ports:
        - containerPort: 80


        